### ISSUE TITLE
Improve metadata() API

### ISSUE THREAD

**Issue by edenhill** [confluentinc/librdkafka#1158]
The current metadata() API is pretty limited, a bit weird, and does not allow the full flexibility of the underlying protocol MetadataRequest.

A new API should be added with a signature something like this:
```
rd_kafka_resp_err_t rd_kafka_metadataX (rd_kafka_t *rk, rd_kafka_topic_partition_list_t *topics, rd_kafka_metadata_t **metadatap, int timeout_ms);
```
This would allow querying for a range of topics.

Additionally, since the metadata format is evolving a new metadata_t type needs to be added to librdkafka which is completely opaque and its implementation hidden from application, so as to allow evolving that type as well, using accessor methods.

**Comment by duncanphillips** [comment]
For Python, we currently use PyKafka because we need the producer partitioning it has available. We would prefer to use confluent-kafka but since we can't inspect metadata, and partitioners are not supported because of the GIL issues mentioned in the code, it looks like we're at a bit of a dead end. Unfortunately my C isn't strong enough to help PR this into librdkafka, so by any chance do you have a rough idea of where this falls in the roadmap?

**Comment by edenhill** [comment]
The new Metadata API will unfortunately not make the June release, the earliest would be end of August, depending on backlog prioritization.

For the partitioner, we're trying to figure out the best approach to go there and the more use-case info we have, the better.
Can you share your partitioner, or what it does?
One approach is for librdkafka to provide a set of builtin partitioners that covers common uses

**Comment by duncanphillips** [comment]
Our use case is pretty simple. We use a hashing partitioner which constructs a hash key using information in the message. The key is then passed through a hashing partitioner to select a partition from the topic partitions. The partitioner we use comes with PyKafka (HashingPartitioner). Then when we send a produce request, we set the partition (and the key even though it's currently ignored).

**Comment by edenhill** [comment]
Thank you.

I wonder if there is ever a case where they hash key is not modulo partition_cnt, because the partition_cnt is the only reason the partitioner might be called from a background thread.
When the partition count is not known at the time of produce() the message is queued until metadata is available at which time all unpartitioned messages are passed through the partitioners (on a background thread) and then transmitted.
If we would allow the application to provide the partitioner hash key (without the partition_cnt modulo) at the time of produce() we could just apply the hash key % partition_cnt in the background thread without a need to call a partitioner callback.

**Comment by duncanphillips** [comment]
i think that would work with the hashing and consistent hashing. It would also still allow some flexibility in that the hash value could be determined by a linear, random, or hashing process done by the user. I can't really think of what else people would require from a partitioner.

**Comment by mxk1235** [comment]
I have a related issue.  It appears that timed out metadata requests appear as `Local: Broker transport error`.
https://github.com/edenhill/librdkafka/blob/ce67923e8b28f0f82034a1af3b3c88375c3f5a7b/src/rdkafka_metadata.c#L52

at this time, i suspect that my Kafka instance may be responding very slowly, and sometimes consumers fail to get metadata.  it would be nice if timeout was exposed.

**Comment by edenhill** [comment]
@mxk1235 Not sure I understand, the metadata() API has a timeout_ms argument for this purpose.

**Comment by mxk1235** [comment]
here is how we patched our local librdkafka branch

`        /* Query any broker that is up, and if none are up pick the first one,
        * if we're lucky it will be up before the timeout */
        rkb = rd_kafka_broker_any_usable(rk, timeout_ms, 1);
        if (!rkb)
        {
                int remains = rd_timeout_remains(ts_end);
                if (rd_timeout_expired(remains))
                        return RD_KAFKA_RESP_ERR__TIMED_OUT;
                return RD_KAFKA_RESP_ERR__TRANSPORT;
        }`

**Comment by edenhill** [comment]
I think the existing behaviour is better, even though it times out it indicates that the transport is not available (i.e., a broker connection), while a later timeout means the request to the broker timed out.

**Comment by emasab** [comment]
This is now provided by the admin API `rd_kafka_DescribeTopics` that can evolve in parallel to the Java one.
