### ISSUE TITLE
Infinity timeout does not work with message.timeout.ms=0

### ISSUE THREAD

**Issue by sboikocv** [confluentinc/librdkafka#2015]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
    The library must treat it as infinity timeout.
    The problem:
        1. rd_kafka_ProduceRequest converts INT_MAX64 to int and get a negative value
        2. than multiply on 1000 and overflow integer one more time and get a positive value
    The behavior is invalid but still sometimes get a false-positive result

How to reproduce
================
1. Set `message.timeout.ms=0` and  `request.required.acks=-1`. Timeout will 
2. Wait monotonic clock reach `17179869075`
3. Enjoi all your requests timeout in several milliseconds 

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thank you for your analysis, will look into it.

**Comment by sarkanyi** [comment]
Can't you simply set the limit to `rkm->rkm_ts_timeout = INT64_MAX - now;` in case of 0? That would avoid the negative value. You still have to fix the linger.ms case.

**Comment by emasab** [comment]
Closed by #2050
