### ISSUE TITLE
Expose `is_internal` from Metadata Response (V2+)

### ISSUE THREAD

**Issue by mlongob** [confluentinc/librdkafka#2057]
Protocol: https://kafka.apache.org/protocol#The_Messages_Metadata

This is already extracted in the Metadata Response parser: https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/src/rdkafka_metadata.c#L313

It would be nice to expose the `is_internal` field in the `rd_kafka_metadata_topic_t` struct:
https://github.com/edenhill/librdkafka/blob/849c066b559950b02e37a69256f0cb7b04381d0e/src/rdkafka.h#L3338-L3343

**Comment by emasab** [comment]
This field is now available in the `DescribeTopics` admin API
