### ISSUE TITLE
How a consumer consumes multiple topics in a pure C environment

### ISSUE THREAD

**Issue by mingtongzaohua** [confluentinc/librdkafka#2278]
Description
===========
I use a pure C language environment. I want a consumer to consume multiple topics, and use pthread to simultaneously obtain data from multiple topics for subsequent processing. But failed, only the last topic was retained.

The example uses 

> static rd_kafka_t *rk;

 Should I change to a queue? Or should I add multiple topics to the 

> rd_kafka_topic_partition_list_t *topics

topics? I have tried both of them and it doesn't seem to work. I'm not sure if I have a problem with the code, or if there is a problem with the idea, can you give me a suggestion?

How to reproduce
================
Consumer code is very confusing and doesn't necessarily help. I tried to modify it based on the example. My goal is for a consumer to consume data from multiple topics at the same time. Currently it is serial, close the link after receiving it, reassign the topic, and then receive it. Can be successful, but there is no doubt that it is very inefficient.

#include "rdkafka.h"
#include "network.h"

static int run = 1; //`rd_kafka_t`自带⼀一个可选的配置API，如果没有调⽤用API，Librdkafka将 会使⽤用CONFIGURATION.md中的默认配置。
static rd_kafka_t *rk;
static rd_kafka_topic_partition_list_t *topics;
static void stop(int sig) {
    if (!run)
        exit(1);
    run = 0;
    fclose(stdin); /* abort fgets() */
}

static void sig_usr1(int sig) {
    rd_kafka_dump(stdout, rk);
}

/** * 处理理并打印已消费的消息 */
static void msg_consume(rd_kafka_message_t *rkmessage, void *opaque,int *buff_length,unsigned char *buff) {
    printf("%%We start get Message (topic %s)!\n",
           rd_kafka_topic_name(rkmessage->rkt));
    
    if (rkmessage->err) {
        if (rkmessage->err == RD_KAFKA_RESP_ERR__PARTITION_EOF) {
            fprintf(stderr,
                    "%% Consumer reached end of %s [%"PRId32"] "
                    "message queue at offset %"PRId64"\n",
                    rd_kafka_topic_name(rkmessage->rkt),
                    rkmessage->partition, rkmessage->offset);
            
            return;
        }
        
        if (rkmessage->rkt)
            fprintf(stderr, "%% Consume error for "
                    "topic \"%s\" [%"PRId32"] "
                    "offset %"PRId64": %s\n",
                    rd_kafka_topic_name(rkmessage->rkt),
                    rkmessage->partition,
                    rkmessage->offset,
                    rd_kafka_message_errstr(rkmessage));
        else
            fprintf(stderr, "%% Consumer error: %s: %s\n",
                    rd_kafka_err2str(rkmessage->err),
                    rd_kafka_message_errstr(rkmessage));
        
        if (rkmessage->err == RD_KAFKA_RESP_ERR__UNKNOWN_PARTITION ||
            rkmessage->err == RD_KAFKA_RESP_ERR__UNKNOWN_TOPIC)
            run = 0;
        return;
    }
    
    fprintf(stdout, "%% Message (topic %s [%"PRId32"], "
            "offset %"PRId64", %zd bytes):\n",
            rd_kafka_topic_name(rkmessage->rkt),
            rkmessage->partition,
            rkmessage->offset, rkmessage->len);
    
    printf("%%We get Message (topic %s [%"PRId32"], "
           "offset %"PRId64", %zd bytes):\n",
           rd_kafka_topic_name(rkmessage->rkt),
           rkmessage->partition,
           rkmessage->offset, rkmessage->len);
    
    if (rkmessage->key_len) {
        printf("Key: %.*s\n",
               (int)rkmessage->key_len, (char *)rkmessage->key);
    }
    
    printf("%d,%.*s\n",
           (int)rkmessage->len,(int)rkmessage->len, (unsigned char *)rkmessage->payload);
    
    *buff_length=rkmessage->len;
    for(int i=0;i<*buff_length;i++)
    {
        buff[i]=((unsigned char *)rkmessage->payload)[i];
    }
}
/*
 init all configuration of kafka
 */
int initKafka(char *brokers, char *group, char *topic) {
    rd_kafka_conf_t *conf;
    rd_kafka_topic_conf_t *topic_conf;
    rd_kafka_resp_err_t err;
    char tmp[16];
    char errstr[512];
    
    /* Kafka configuration */
    conf = rd_kafka_conf_new();
    
    //quick termination
    snprintf(tmp, sizeof(tmp), "%i", SIGIO);
    rd_kafka_conf_set(conf, "internal.termination.signal", tmp, NULL, 0);
    
    //topic configuration
    topic_conf = rd_kafka_topic_conf_new();
    
    /* Consumer groups require a group id */
    if (!group)
        group = "rdkafka_consumer_example";
    if (rd_kafka_conf_set(conf, "group.id", group, errstr, sizeof(errstr))
        != RD_KAFKA_CONF_OK) {
        fprintf(stderr, "%% %s\n", errstr);
        printf("rd_kafka_new error\n");
        return -1;
    }
    
    /* Consumer groups always use broker based offset storage */
    if (rd_kafka_topic_conf_set(topic_conf, "offset.store.method", "broker",
                                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) {
        fprintf(stderr, "%% %s\n", errstr);
        return -1;
    }
    
    /* Set default topic config for pattern-matched topics. */
    rd_kafka_conf_set_default_topic_conf(conf, topic_conf);
    
    //实例化⼀个顶级对象rd_kafka_t作为基础容器，提供全局配置和共享状态
    rk = rd_kafka_new(RD_KAFKA_CONSUMER, conf, errstr, sizeof(errstr));
    if (!rk) {
        fprintf(stderr, "%% Failed to create new consumer:%s\n", errstr);
        return -1;
    }
    printf("kafka initKafka\n");
    //Librdkafka需要⾄少⼀个brokers的初始化list
    if (rd_kafka_brokers_add(rk, brokers) == 0) {
        fprintf(stderr, "%% No valid brokers specified\n");
        return -1;
    }
    
    //重定向 rd_kafka_poll()队列到consumer_poll()队列
    rd_kafka_poll_set_consumer(rk);
    
    //创建⼀个Topic+Partition的存储空间(list/vector)
    topics = rd_kafka_topic_partition_list_new(1);
    //把Topic+Partition加⼊list
    rd_kafka_topic_partition_list_add(topics, topic, -1);
    //开启consumer订阅，匹配的topic将被添加到订阅列表中
    if ((err = rd_kafka_subscribe(rk, topics))) {
        fprintf(stderr, "%% Failed to start consuming topics: %s\n",
                rd_kafka_err2str(err));
        return -1;
    }
    return 1;
}

void networkzh(void *threadarg) {
    struct AP_Data *ap_data = (struct AP_Data *) threadarg;
    char *brokers = ap_data->brokers;
    char *group = NULL;
    char *topic = ap_data->topic;
    printf("kafka server start!\n");
    printf("brokers:%s\n",brokers);
    printf("group:%s\n",group);
    printf("topic:%s\n",topic);
    
    int opt;
    rd_kafka_resp_err_t err;
    
    signal(SIGINT, stop);
    signal(SIGUSR1, sig_usr1);
    unsigned char *buff = (unsigned char *) malloc(
                                                   sizeof(unsigned char) * BUFSIZ);
    ap_data->csi_buff_length = 0;
    int packet_cnt = 0;
    int buff_length=0;
    
    if (!initKafka(brokers, group, topic)) {
        printf("kafka server initialize error\n");
        fprintf(stderr, "kafka server initialize error\n");
    } else {
        printf("kafka server initialize success\n");
        while (packet_cnt < NUM_PACKETS) {
            printf("kafka packet_cnt:%d\n",packet_cnt);
            rd_kafka_message_t *rkmessage;
            /*-轮询消费者的消息或事件，最多阻塞timeout_ms
             -应⽤程序应该定期调⽤consumer_poll()，即使没有预期的消息，
             以服务
             所有排队等待的回调函数，当注册过rebalance_cb，该操作尤为
             重要，
             因为它需要被正确地调⽤和处理以同步内部消费者状态 */
            rkmessage = rd_kafka_consumer_poll(rk, 1000);
            printf("topic:%s\n",topic);
            printf("rkmessage , rkmessage:%d!\n", rkmessage);
            if (rkmessage) {
                printf("rkmessage success, rkmessage:%d!\n", rkmessage);
                msg_consume(rkmessage, NULL,&buff_length,buff);
                /*释放rkmessage的资源，并把所有权还给rdkafka*/
                rd_kafka_message_destroy(rkmessage);
            }
            if (buff_length <= 0) {
                printf("recv error, buff_length:%d!\n", buff_length);
                continue;
            }
            memcpy(ap_data->csi_buff + (ap_data->csi_buff_length), buff,
                   buff_length);
            (ap_data->csi_buff_length) += buff_length;
            packet_cnt++;
            buff_length=0;
            
            if (packet_cnt % 20 == 0)
                printf(
                       "server port:%d packet_cnt:%d recv from topic %s message's size:%dB\n",
                       ap_data->port, packet_cnt,
                       ap_data->topic,
                       buff_length);
            
        }
    }//end if init
    
done:
    err = rd_kafka_consumer_close(rk);
    if (err) {
        fprintf(stderr, "%% Failed to close consumer: %s\n",
                rd_kafka_err2str(err));
    } else {
        fprintf(stderr, "%% Consumer closed\n");
    }
    
    //释放topics list使⽤的所有资源和它⾃⼰
    rd_kafka_topic_partition_list_destroy(topics);
    
    //destroy kafka handle
    rd_kafka_destroy(rk);
    
    run = 5;
    //等待所有rd_kafka_t对象销毁，所有kafka对象被销毁，返回0，超时返s回 - 1
    while (run-- > 0 && rd_kafka_wait_destroyed(1000) == -1) {
        printf("Waiting for librdkafka to decommission\n");
    }
    if (run <= 0) {
        //dump rdkafka内部状态到stdout流
        rd_kafka_dump(stdout, rk);
    }
    //        return 0;
}

void network_multi_ap(unsigned char *all_csi_buff, int *all_cai_buff_length) {
    pthread_t threads[NUM_AP];
    struct AP_Data *aps_data = (struct AP_Data *) malloc(
                                                         sizeof(struct AP_Data) * NUM_AP);
    
    for (int i = 0; i < NUM_AP; i++) {
        aps_data[i].ap_id = i;
        aps_data[i].port = INIT_PORT + i;
        
        sprintf(aps_data[i].topic,"%d",i);
        printf("pthread_create error: error_code:");
        printf("aps_data[i].topic:%s\n",aps_data[i].topic);
        printf("aps_data[i].brokers:%s\n",aps_data[i].brokers);
        //        if (!initKafka(brokers, group, topic)) {
        //                printf("kafka server initialize error\n");
        //                fprintf(stderr, "kafka server initialize error\n");
        //        }
        //        int ret = pthread_create(&(threads[i]), NULL, networkzh,(void*) &(aps_data[i]));
        networkzh((void*) &(aps_data[i]));
        //        if (ret != 0) {
        //            printf("pthread_create error: error_code = %d\n", ret);
        //            exit(-1);
        //        }
    }
    //    for (int i = 0; i < NUM_AP; i++) {
    //        int join_ret = pthread_join(threads[i], NULL);
    //        if (join_ret != 0) {
    //            printf("cannot join thread[%d]\n", i);
    //            exit(-1);
    //        }
    //    }
    
    *all_cai_buff_length = 0;
    for (int i = 0; i < NUM_AP; i++) {
        memcpy(all_csi_buff + (*all_cai_buff_length), aps_data[i].csi_buff,
               aps_data[i].csi_buff_length);
        (*all_cai_buff_length) += aps_data[i].csi_buff_length;
    }
    printf("all_csi_buff_length:%dB\n", *all_cai_buff_length);
    
    free(aps_data);
}

**Comment by emasab** [comment]
Please check the example for how to consume multiple topics. Also consumer should be accessed from a single thread, only the the message can be assigned to different threads for processing.

https://github.com/confluentinc/librdkafka/blob/6eaf89fb124c421b66b43b195879d458a3a31f86/examples/consumer.c#L172
