### ISSUE TITLE
snappy-c: Failed to build with MSVC running on ARM

### ISSUE THREAD

**Issue by myd7349** [confluentinc/librdkafka#2324]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Current implementation of [`get_unaligned_memcpy` and `put_unaligned_memcpy`](https://github.com/edenhill/librdkafka/blob/v1.0.0/src/snappy_compat.h#L47-L53) relies on some GCC specific extensions:
1. typeof
2. statements expressions

and it will cause build errors with MSVC running on ARM: https://github.com/microsoft/vcpkg/pull/5921#issuecomment-490330000

Rewriting these two macros with some inline functions may fix this problem: https://github.com/myd7349/librdkafka/commit/cd5e98c607ed7367f7a0ff307f724443425197ed
Some code in this patch is borrowed from: https://github.com/google/snappy/blob/1.1.7/snappy-stubs-internal.h#L209-L237

How to reproduce
================
Install `librdkafka` through `vcpkg` with this command:
> vcpkg install librdkafka:arm64-windows

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `dc85ffc8068c18dfdf118666b4c78de1c7ac640b`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you want to make a PR for this change?

**Comment by myd7349** [comment]
> 
> 
> Do you want to make a PR for this change?

Hi! @edenhill Thanks for your interest in this patch.  If this fix works for ARM: https://github.com/microsoft/vcpkg/pull/5921#issuecomment-494330889, I'd like to create a PR for it.
