### ISSUE TITLE
[question] why called rdkafka, what does rd  represent?

### ISSUE THREAD

**Issue by feng1o** [confluentinc/librdkafka#2586]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
sorry, i just want to know why called librdkafka?  what is the meaning of 'rd'! thanks

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#whats-the-meaning-of-rd-in-librdkafka

**Comment by feng1o** [comment]
> 
> 
> https://github.com/edenhill/librdkafka/wiki/FAQ#whats-the-meaning-of-rd-in-librdkafka

got it, thank you very much

**Comment by jbaldwin** [comment]
I thought it stood for "liberty kafka" if you phonetically pronounce it, but interesting to see why it was actually named rd-kafka.
