### ISSUE TITLE
KIP-368: Allow SASL Connections to Periodically Re-Authenticate

### ISSUE THREAD

**Issue by vctoriawu** [confluentinc/librdkafka#3304]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Hello!

Description
===========
Currently, librdkafka does not provide support for periodic reauthentication of SASL connections as described in KIP-368 (https://cwiki.apache.org/confluence/display/KAFKA/KIP-368:+Allow+SASL+Connections+to+Periodically+Re-Authenticate). We are hoping to implement this feature on the client side. Based on the proposed changes, we came up with the following implementation:

- Specify a callback function in the config that gets/refreshes token info
- When the client receives the initial SASLAuthenticate response from the broker, parse the response to find the expiration time of the connection (in rd_kafka_handle_SASLAuthenticate)
- Store the expiration time retrieved into rk_trans
- When a message is about to be sent, check whether the current time is within a threshold/past the expiration time stored in the rktrans. This check would happen around rd_kafka_send (based on the Java code implementation which checks this during each attempted write, triggered from the poll https://github.com/apache/kafka/pull/5582) 
- If the expiration time is within threshold/past, process the original API versions response to get the API version (ensure this feature is supported)
- Then send a handshake request by calling rd_kafka_SASLHandshakeRequest
- Trigger the callback function to refresh token info
- Once we have refreshed the token, reauthenticate the connection by calling rd_kafka_SASLAuthenticate
- On the SASLAuthenticateResponse, we will get a new expiration time associated with the SASL connection, which will get stored in the rk_trans, and this whole process will happen again 
- While the reauthentication is occurring, store the message that triggered the reauthentication and all subsequent messages , then send them once reauthentication has succeeded

Is this the right method to accomplish what is required? Any feedback or input would be greatly appreciated. Thanks!

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.6.0
 - [x] Apache Kafka version: 2.6
 - [x] librdkafka client configuration: security.protocol = sasl_plaintext, sasl_ssl; sasl.mechanism = OAUTHBEARER
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for looking into this feature!

 > * Specify a callback function in the config that gets/refreshes token info

What token information is that? OAUTHBEARER? If so, there's already a refresh callback for that.

> Store the expiration time retrieved into rk_trans

Authentication is not a transport-level thing in librdkafka (as opposed to the Java clients), so this state should be kept on the `rkb` (broker_t).

I think it might be cleaner to add a reauth timer on the rkb and once that timer hits transition to a new BROKER_STATE_REAUTH_DRAIN state that holds back any new sends and waits for all outstanding requests to finish. And when that is done transitions to the AUTH state to re-authenticate.

> When a message is about to be sent, check whether the current time..

I think it might be

**Comment by vctoriawu** [comment]
@tombentley we did, will submit a PR next week

**Comment by vctoriawu** [comment]
@tombentley @showuon here is the initial PR: https://github.com/edenhill/librdkafka/pull/3754 any feedback would be greatly appreciated

**Comment by showuon** [comment]
@vctoriawu , that's great! I'll check the PR next week! Thank you.

**Comment by milindl** [comment]
Closing with #4301
