### ISSUE TITLE
examples/misc fails with OAUTHBEARER

### ISSUE THREAD

**Issue by jkt628** [confluentinc/librdkafka#3753]
Description
===========
i have a custom plugin that refreshes the OAUTHBEARER token using some internal provider.  this works fine for consumers and producers because they call `poll()`; however, https://github.com/edenhill/librdkafka/blob/master/examples/misc.c goes straight to `rd_kafka_list_groups()` which fails to establish any connection to any broker.

How to reproduce
================
```bash
examples/misc -b kafka:9093 -X sasl.mechanisms=OAUTHBEARER -X security.protocol=SASL_PLAINTEXT -X plugin.library.paths=$PLUGINS/fetch_token.so list_groups
```

i found the same issue with `kcat -L -b kafka:9093 -X sasl.mechanisms=OAUTHBEARER -X security.protocol=SASL_PLAINTEXT -X plugin.library.paths=$PLUGINS/fetch_token.so`.

i suspect the internal `sasl.oauthbearer.method=oidc` may have a similar issue but did not set up any test.

based on #3556 i created the following patch which does refresh the token and works.

```text
diff --git a/examples/misc.c b/examples/misc.c
index 3c696d79..ca0908a3 100644
--- a/examples/misc.c
+++ b/examples/misc.c
@@ -157,6 +157,7 @@ static void cmd_list_groups(rd_kafka_conf_t *conf, int argc, char **argv) {
         /*
          * List groups
          */
+        rd_kafka_poll(rk, 0);
         err = rd_kafka_list_groups(rk, groupid, &grplist, 10 * 1000 /*10s*/);
         if (err)
                 fatal("rd_kafka_list_groups(%s) failed: %s", groupid,
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `5ec06ef6ede3aa3692b90579018eebfa36026464` (HEAD when submitted)
 - [x] Apache Kafka version: `Confluent 5.5.5 / Kafka 2.5.X`
 - [x] librdkafka client configuration: `-X sasl.mechanisms=OAUTHBEARER -X security.protocol=SASL_PLAINTEXT -X plugin.library.paths=$PLUGINS/fetch_token.so -X debug=all`
 - [x] Operating system: `Kubuntu 21.10`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts (N/A)
 - [ ] Critical issue

```text
%7|1646262791.365|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider OAUTHBEARER (builtin) for SASL mechanism OAUTHBEARER
%7|1646262791.366|WAKEUPFD|rdkafka#consumer-1| [thrd:app]: sasl_plaintext://kafka:9093/bootstrap: Enabled low-latency ops queue wake-ups
%7|1646262791.366|BRKMAIN|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1646262791.366|BROKER|rdkafka#consumer-1| [thrd:app]: sasl_plaintext://kafka:9093/bootstrap: Added new broker with NodeId -1
%7|1646262791.366|CONNECT|rdkafka#consumer-1| [thrd:app]: sasl_plaintext://kafka:9093/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1646262791.366|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.9.0 (0x10900ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer, CMAKE GNU GNU PKGCONFIG HDRHISTOGRAM ZLIB LIBDL PLUGINS SSL SASL_SCRAM SASL_OAUTHBEARER SASL_CYRUS C11THREADS CRC32C_HW SNAPPY SOCKEM, debug 0xfffff)
%7|1646262791.366|BRKMAIN|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka:9093/bootstrap]: sasl_plaintext://kafka:9093/bootstrap: Enter main broker thread
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]: Client configuration:
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   client.software.version = 1.9.0
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   metadata.broker.list = kafka:9093
%7|1646262791.366|CONNECT|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka:9093/bootstrap]: sasl_plaintext://kafka:9093/bootstrap: Received CONNECT op
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   debug = generic,broker,topic,metadata,feature,queue,msg,protocol,cgrp,security,fetch,interceptor,plugin,consumer,admin,eos,mock,assignor,conf,all
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   security.protocol = sasl_plaintext
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   sasl.mechanisms = OAUTHBEARER
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   oauthbearer_token_refresh_cb = 0x7fb4f2e9d560
%7|1646262791.366|CONF|rdkafka#consumer-1| [thrd:app]:   plugin.library.paths = /tmp/fetch_token.so
%7|1646262791.366|STATE|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka:9093/bootstrap]: sasl_plaintext://kafka:9093/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1646262791.366|BROADCAST|rdkafka#consumer-1| [thrd:sasl_plaintext://kafka9093/bootstrap]: Broadcasting state change
%7|1646262792.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262793.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262794.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262795.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262796.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262797.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262798.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262799.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262800.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1646262801.366|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
ERROR: rd_kafka_list_groups((null)) failed: Local: Timed out
```

**Comment by edenhill** [comment]
Yeah, this is tricky. We can't call the refresh callback from rd_kafka_new() because the application or high-level language bindings may not be fully initialized prior to rd_kafka_new() returning.

And we can't really trigger the refresh callback from various APIs, like list_groups(), either, because that's an unexpected side-effect.

One solution would be to trigger it from a background thread, but that means the callback will not be called in the application thread which is sort of a contract that we have for other callbacks.

Not sure what the best solution is really.

**Comment by edenhill** [comment]
The contract is that it's triggered from poll() (et.al).
An application can also enable background sasl callbacks by calling `rd_kafka_conf_enable_sasl_queue()` as documented here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2085-L2112

But that also requires code change in the application, so doesn't really help.

Even if there was no contract to have it called from poll() but instead a background thread by default, we can't really do that without a synchronization point / API call, because without any synchronization between the application code and librdkafka the background thread could fire off the refresh callback before rd_kafka_new() has returned, this is especially true for high-level languages (since they're slower).

**Comment by anchitj** [comment]
Closing as we need to explicitly call poll() once after creating the client to trigger the oauth callback.
