### ISSUE TITLE
Crash in rd_kafka_flush() if the connection is TLS.

### ISSUE THREAD

**Issue by Animesh-ctrl** [confluentinc/librdkafka#3854]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Precondition: Kafka Broker is down.
If the connection is over TCP then it's working as expected, but if we use TLS then it's crashing in rd_kafka_flush() API.

How to reproduce
================
1. Stop the Kafka service on the broker by executing systemctl stop kafka.
2. Producer starts sending the messages, and we received the timeout at the producer end and observed the crash.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.6`

**Comment by mhowlett** [comment]
We will investigate if the issue reproduces in the latest version, but I expect it is most likely resolved.
