### ISSUE TITLE
about the parameter 'group.id' and the consumer group name

### ISSUE THREAD

**Issue by xiaoshizijiayou** [confluentinc/librdkafka#3865]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ
Description
I use the consumer interface,but i  forget to set the param 'group.id'.It runs normals for a long time .Now i want to use the 'kafka-consumer-groups.sh' to see the consumer-groups information,It returns is empty.What is the default value of consumer groups when i don't set the 'group.id'.

![image](https://user-images.githubusercontent.com/26808449/171324690-128ca6e1-0159-4020-b78a-a818de8dcec5.png)

How to reproduce
because of the interruption of power supply, the kafka server is down for 3 days.when i restart the server and service, the consumer starts to consume from now.i may need to reset the offset of kafka to consume the data of 3 days.But i can't get the consumer-groups name ,i don't know how to deal this.please help me!thanks  a lot!

Checklist

- [x ] librdkafka version：v0.11.1

- [ x] Apache Kafka version:kafka_2.12-2.4.1

- [x ] librdkafka client configuration：session.timeout.ms=6000，auto.offset.reset=earliest

- [ x] Operating system:cenos7(x64)

**Comment by tlegrand54** [comment]
Hello, the default value of the group.id is null.
you can find more information at : https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#ak-consumer-configurations-for-cp

**Comment by milindl** [comment]
`kafka-consumer-groups.sh` is bundled with Apache Kafka, it's not a part of librdkafka. You can try a mailing list from here: https://kafka.apache.org/contact if this still persists.
