### ISSUE TITLE
Messages only delivered to one partition (others run into timeout)

### ISSUE THREAD

**Issue by paul-bormans** [confluentinc/librdkafka#3878]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
On a test setup we noticed only a single broker (running 3 brokers and topics have 3 partitions) was receiving data; this was the case for all the topics (+/- 10 topics in total). We managed to reproduce the issue using kcat for which logging is attached to this ticket.

We tried several variations to pinpoint the root-cause:
1) We ran the producing client to another machine/subnet which worked OK
2) We ran against a different/newly setup broker backend which was NOK

When trying to reproduce using kcat we noticed messages are delivered to all 3 partitions when the load is low (say up to 100 messages of only a string "hello world"), but when we scale to 1000 messages (also tiny) then we notice that 1/3 of the messages is delivered to one partitions and the others don't get any, logging shows a connection timeout 60054ms and even on reconnects it doesn't get delivered.

Section of first timeout:

%5|1655386753.517|REQTMOUT|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: Timed out ProduceRequest in flight (after 60054ms, timeout #0)
%7|1655386753.517|REQERR|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: ProduceRequest failed: Local: Timed out: explicit actions Retry,MsgPossiblyPersisted
%7|1655386753.517|MSGSET|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: MY_TOPIC [2]: MessageSet with 322 message(s) (MsgId 0, BaseSeq -1) encountered error: Local: Timed out (actions Retry,MsgPossiblyPersisted)
%4|1655386753.517|REQTMOUT|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%7|1655386753.517|BROKERFAIL|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: failed: err: Local: Timed out: (errno: Connection timed out)
%7|1655386753.517|STATE|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: Broker changed state UP -> DOWN
%7|1655386753.517|BROADCAST|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: Broadcasting state change
%7|1655386753.517|BUFQ|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: Purging bufq with 0 buffers
%7|1655386753.517|BUFQ|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: Purging bufq with 0 buffers
%7|1655386753.517|BUFQ|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker1:31220/0: Updating 0 buffers on connection reset
%7|1655386753.517|METADATA|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: Requesting metadata for 1/1 topics: broker down
%7|1655386753.517|METADATA|rdkafka#producer-1| [thrd:ssl://broker1:31220/0]: ssl://broker2:31221/1: Request metadata for 1 topic(s): broker down
% ERROR: Local: Timed out: ssl://broker1:31220/0: 1 request(s) timed out: disconnect (after 60054ms in state UP)

How to reproduce
================
- librdkafka 1.1.0 (i know it's pretty old but it's ... difficult to upgrade dependencies in our project)
- running kcat with following options:

`./kcat \
    -b broker3-full:31220/2 \
    -t MY_TOPIC \
    -X security.protocol=SSL \
    -X ssl.ca.location=dev85_cert \
    -X queue.buffering.max.kbytes=1776000 \
    -X queue.buffering.max.ms=50 \
    -X retry.backoff.ms=100 \
    -X message.send.max.retries=3 \
    -X statistics.interval.ms=10000 \
    -X debug=all \
    -X socket.keepalive.enable=true \
    -X acks=all \
    -l \
    -P messages-1000.dat
`

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.1.0
 - [x] Apache Kafka version: Confluent Kafka 6.1.0 == 2.7.0
 - [x] librdkafka client configuration: 
                -X security.protocol=SSL \
                -X ssl.ca.location=dev85_cert \
                -X queue.buffering.max.kbytes=1776000 \
                -X queue.buffering.max.ms=50 \
                -X retry.backoff.ms=100 \
                -X message.send.max.retries=3 \
                -X statistics.interval.ms=10000 \
                -X debug=all \
                -X socket.keepalive.enable=true \
                -X acks=all \
 - [x] Operating system: CentOS release 6.8 (Final)
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
[kcat_1000messages_nok_edit.log.gz](https://github.com/edenhill/librdkafka/files/8919544/kcat_1000messages_nok_edit.log.gz)
![20220616_capture_kafdrop](https://user-images.githubusercontent.com/78035262/174088880-e9834719-24eb-482f-87c7-166550fab874.PNG)

**Comment by paul-bormans** [comment]
We ran some additional tests with kcat / librdkafka 1.9.0 and specifically we ran PLAINTEXT vs SSL. This shows that we only see the issue when using SSL protocol. My first guess is the validity of the crt's but those are all valid/ok; tested with openssl s_client -connect...

Please find two logfile; one using plaintext and the other ssl.

[kcat_1_9_0_1000messages_ok_7_plaintext_edit.txt](https://github.com/edenhill/librdkafka/files/8940541/kcat_1_9_0_1000messages_ok_7_plaintext_edit.txt)
[kcat_1_9_0_1000messages_nok_ssl_8_edit.txt](https://github.com/edenhill/librdkafka/files/8940542/kcat_1_9_0_1000messages_nok_ssl_8_edit.txt)

Any idea's/tip's?

**Comment by paul-bormans** [comment]
Hello Magnus,

Thanks for the tip/idea; we ran a test this morning but with same timeout as a result. Attaching logs for that run as well.

From the logfiles i can see that an ApiVersionRequest is send and a response is properly received but then directly after the request with the MessageSet gets a timeout (all on the same endpoint). I assume this is run over the same open connection so i'm puzzled why the latter fails? Is there any verbose logging i could enable on the backend (which is a Confluence construct btw) that could reveal if the request is received at all? (i.e. or blocked by maybe a network component in the wire?).

Paul
[kcat_1_9_0_1000messages_nok_9_ssl_ack1_edit.txt](https://github.com/edenhill/librdkafka/files/8947895/kcat_1_9_0_1000messages_nok_9_ssl_ack1_edit.txt)

**Comment by edenhill** [comment]
You could enable debug/tracing on the broker and look in the logs for hints, but that's outside my area of expertise.
I don't believe this to be a client issue.

**Comment by paul-bormans** [comment]
I tend to agree with you Magnus, not a client issue. But allow me to update this ticket with findings that may hopefully help others seeing something similar.

**Comment by paul-bormans** [comment]
I managed to run wireshark on the backend (broker host) and decode the encrypted content (SSL remember). It shows that the initial ProduceRequest is in fact properly received at the backend, and also it seems an ACK is send back, but then a retransmission is requested?

![wireshark capture](https://user-images.githubusercontent.com/78035262/175980521-f815496a-2811-4cc6-9c75-3f79c760802b.png)

Conclusion: not a backend issue as well?

I'll try to capture at the producing side as well to trace the ACK message.

To be continued....

It has been a nice challenge btw to get the encrypted payload decoded; roughly what i did:
1) Compile wireshark from source (since default package manager installed an ancient version missing Kafka dissector.
2) Run tshark on the broker host with following options: "tshark -V -i eth0 -d tcp.port=<port-used>,kafka -f 'host <producer-host-ip>'"
3) Run kcat/librdkafka with limited cipher suite (to exclude DH): " -X ssl.cipher.suites=AES256-GCM-SHA384 "
4) Then download/decode the private key the broker is using (obviously only an option for powerusers)
5) Then load the files into Wireshark and select decoding to use TLS field and Kafka dissector.

**Comment by paul-bormans** [comment]
@edenhill In the end it appeared to be a networking issue, specifically a MTU issue. The network path from producer to consumer is complex with many "hops" and firewalls. Somehowthe so-called PMTUD (lowest mtu discovery) didn't come through and as a result the producer and consumer were using best-guess mtu's (with DF bit set), somewhere on one of these hops packets can't be send through because of a lower max packet size. A quick workaround is to lower mtu setting on the network device to the lower value (the next hop value in the ICMP message). For others running into this same issue; consult with network teams/experts to get a proper solution.
