### ISSUE TITLE
sasl.jaas.config support

### ISSUE THREAD

**Issue by daihanhle** [confluentinc/librdkafka#4119]
Hello,

I use the kafka version 1.9..2.

rd_kafka_conf_set return error when it reads "sasl.jaas.config" config option.

does sasl.jaas.config support by library ? any work around ?

DH

Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by kocic11** [comment]
No, it doesn't support sasl.jaas.config.

Instead, use the following librdkafka properties:
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.username=<username>
sasl.password=<token>

**Comment by lcmgh** [comment]
When setting security.protocol=SASL_SSL I am getting  `Consumer creation failed: KafkaError (Client config error: Unsupported value "SASL_SSL" for configuration property "security.protocol": OpenSSL not available at build time security.protocol SASL_SSL)`
