### ISSUE TITLE
[Vulnerability] Veracode scans libssl.so.1.0.0.so for librdkafka.so v1.9.2

### ISSUE THREAD

**Issue by jhonambrad** [confluentinc/librdkafka#4145]
### Discussed in https://github.com/confluentinc/librdkafka/discussions/4144

<div type='discussions-op-text'>

<sup>Originally posted by **jhonambrad** January 12, 2023</sup>
Our software component analysis scan tags us of using `libssl.so.1.0.0` (which we are not). Upon further digging, `libssl.so.1.0.0` only appears in the `librdkafka.so` files in `runtimes\linux-x64\native`.
![image](https://user-images.githubusercontent.com/93998916/211879065-1d59c95e-b9aa-498c-9977-5333b4746c6a.png)

Is this version of libssl (1.0.0) actually being used in librdkafka.so v1.9.2? 
If not, what version of OpenSSL is actually being used in librdkafka? 

Thanks alot.</div>

**Comment by emasab** [comment]
librdkafka.redist v1.9.2, the .NET package, can be linked with version of OpenSSL up to 1.1.1q. What you see there is the version of the _symbol_, to see which version is actually linked you should use `ldd`. In this version libssl/libcrypto are not statically compiled and bundled with librdkafka
