### ISSUE TITLE
cJSON & thread-safety

### ISSUE THREAD

**Issue by filimonov** [confluentinc/librdkafka#4159]
cJSON used in librdkafka is not thread-safe (and it is [documented](https://github.com/DaveGamble/cJSON#thread-safety) / expected), 

We [found](https://github.com/ClickHouse/ClickHouse/pull/43259#issuecomment-1403658906)  that when we accidentally did link cJSON from librdkafka with another library which should use a patched version of cJSON (with some [changes to make it thread-safe](https://github.com/aws/aws-sdk-cpp/pull/2231)), and thread-sanitizer was very unhappy about cJSON from librdkafka.

I don't see the synchronization around `cJSON_Parse` calls in librdkafka code. And since librdkafka is multithreaded / thread-safe lib - maybe it should apply a similar patch to cJSON? (or add some synchronization around).

P.S. I've also opened https://github.com/DaveGamble/cJSON/issues/732

**Comment by rolandyoung** [comment]
I note that
1. The cJSON documentation says that cJSON is thread safe as long as
     - `cJSON_GetErrorPtr` is never used - librdkafka does not use this
     - `cJSON_InitHooks` is only ever called before using cJSON in any threads - librdkafka calls `cJSON_InitHooks` only in `rd_kafka_global_init0`
     -  `setlocale` is never called before all calls to cJSON functions have returned - librdkafka does not call `setlocale`. 
2.  librdkafka uses cJSON only in the context of supporting SASL authentication.

It appears, therefore, that librdkafka does not need any synchronization around its use of cJSON.

However, it maybe worth noting that if a client application uses SASL authentication, it should not call setlocale while any librdkafka connection is active (unless it is possible to predict when such a connection might be re-authenticated.) I doubt that it would be possible to lift this restriction by any synchronization internal to librdkafka.

**Comment by filimonov** [comment]
> It appears, therefore, that librdkafka does not need any synchronization around its use of cJSON.

Yes. But thread-sanitizer (we run it as a part of CI/CD) is not happy with that code anyway. Once 2 threads try to do cJSON_Parse -  they both start updating the global var inside cJSON. Even if that does not end up with any crashes etc, the code is not clean.

**Comment by filimonov** [comment]
If you don't mind - I can send a PR similar to https://github.com/aws/aws-sdk-cpp/pull/2231

**Comment by rolandyoung** [comment]
I'm not a maintainer here, but I reckon that such a PR might get accepted (I doubt anything will change otherwise.) It would be even better if you could get a similar PR accepted on the upstream project.
