### ISSUE TITLE
SHA256 checksums of all releases no longer match the actual artifact

### ISSUE THREAD

**Issue by ziggythehamster** [confluentinc/librdkafka#4167]
This appears to have happened in the past few days. The published checksums for all of the releases no longer match the actual checksums. This makes anyone who is checking them fail to verify the files. I do not know the root cause of this. It could be someone rewrote history (which is very bad and needs an announcement if so!) or it could be a GitHub bug.

This is breaking downstream projects like https://github.com/appsignal/rdkafka-ruby, who are verifying package downloads.

Examples:

* v2.0.2.tar.gz should have `f321bcb1e015a34114c83cf1aa7b99ee260236aab096b85c003170c90a47ca9d` but has `d4c313704a9f8f96a0e60db93d6eaf7515a926ad229c8a01dccb7b4a06756619`
* v1.8.2.tar.gz should have `6a747d293a7a4613bd2897e28e8791476fbe1ae7361f2530a876e0fd483482a6` but has `0a02e02685bc10668519eb7c1f7d7a28fffba92be5275cd9c4891c18aebdbb64`

**Comment by ziggythehamster** [comment]
MacPorts is hosting files for some releases that match the published sha256sums: https://distfiles-origin.macports.org/librdkafka/

**Comment by ziggythehamster** [comment]
As pointed out on [ruby.social](https://ruby.social/@george/109780954833581338) by @georgeclaghorn, this appears to be [a change that GitHub is (was?) doing](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/).

**Comment by milindl** [comment]
It seems that checksums (even on Github) are now matching the artifacts, as Github has reverted this change. 

eg:
```
$ sha256sum librdkafka-2.0.2.tar.gz 
f321bcb1e015a34114c83cf1aa7b99ee260236aab096b85c003170c90a47ca9d  librdkafka-2.0.2.tar.gz
```

I'm closing this for now, please reopen this if the issue occurs again, thanks.
