### ISSUE TITLE
rdkafka_sasl_win32 - 'buffers[1].cbBuffer < 4' is always true.

### ISSUE THREAD

**Issue by pavel-pimenov** [confluentinc/librdkafka#4175]
Description
===========
<your issue description goes here>

https://github.com/confluentinc/librdkafka/blob/master/src/rdkafka_sasl_win32.c#L402
buffers[1].cbBuffer   = 0;
https://github.com/confluentinc/librdkafka/blob/master/src/rdkafka_sasl_win32.c#L390

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/confluentinc/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
@pavel-pimenov that should be changed by the DecryptMessage call. Are you getting any error? Please add further details and complete the new issue template.

**Comment by emasab** [comment]
Closing, feel free to reopen with more details.
