### ISSUE TITLE
Out of the box test failure:  0105-transactions_mock.c/do_test_txn_concurrent_operations

### ISSUE THREAD

**Issue by eig** [confluentinc/librdkafka#4181]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
Out of the box test failure: 0105-transactions_mock.c/do_test_txn_concurrent_operations.
No warnings / errors during build.
Consistent on both Debian and Windows 11.

How to reproduce
================
Built with GCC 10.3.0-GLIBC2.17-gold

% ./configure
% make
% cd tests
% make run_local

Log:

[<MAIN>                      /397.101s] ALL-TESTS: duration 397100.844ms
[<MAIN>                      /397.102s] 6 thread(s) in use by librdkafka, waiting...
REFCNT DEBUG: &(rkb)->rkb_refcnt                  3 +1:   0x7b7800018f88: rd_kafka_connect_any:5488
%7|1675710043.503|CONNECT|0105_transactions_mock#producer-56| [thrd:main]: 127.0.0.1:45667/bootstrap: Selected for cluster connection: no cluster connection (broker has 22 connection attempt(s))
REFCNT DEBUG: &(rkb)->rkb_refcnt                  4 -1:   0x7b7800018f88: rd_kafka_connect_any:5509
%7|1675710043.504|CONNECT|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Received CONNECT op
%7|1675710043.504|STATE|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1675710043.504|CONNECT|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: broker in state TRY_CONNECT connecting
%7|1675710043.504|STATE|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1675710043.504|CONNECT|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Connecting to ipv4#127.0.0.1:45667 (plaintext) with socket 15
%7|1675710043.504|CONNECT|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Connected to ipv4#127.0.0.1:45667
%7|1675710043.504|CONNECTED|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Connected (#23)
%7|1675710043.504|FEATURE|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1675710043.504|STATE|0105_transactions_mock#producer-56| [thrd:127.0.0.1:45667/bootstrap]: 127.0.0.1:45667/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
REFCNT DEBUG: (&(rkb)->rkb_refcnt)                3 +1:   0x7b7800018f88: rd_kafka_buf_new_request0:147
REFCNT DEBUG: (&(rkbuf->rkbuf_rkb)->rkb_refcnt)   3 +1:   0x7b780002af88: rd_kafka_mock_connection_read_request:875
REFCNT DEBUG: &(rkbuf)->rkbuf_refcnt              1 -1:   0x7b540001bbb0: rd_kafka_mock_connection_io:1184
REFCNT DEBUG: &(rkbuf->rkbuf_rkb)->rkb_refcnt     4 -1:   0x7b780002af88: rd_kafka_buf_destroy_final:75
REFCNT DEBUG: (&(rkbuf->rkbuf_rkb)->rkb_refcnt)   3 +1:   0x7b780002af88: rd_kafka_mock_connection_read_request:875
%7|1675710043.511|CONNECT|0105_transactions_mock#producer-56| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 42ms: acquire ProducerID
[0105_transactions_mock      /397.243s] Waiting for main thread to finish init_transactions()
%7|1675710043.518|CONNECT|0105_transactions_mock#producer-56| [thrd:TxnCoordinator]: TxnCoordinator: broker in state TRY_CONNECT connecting
%7|1675710043.518|CONNECT|0105_transactions_mock#producer-56| [thrd:TxnCoordinator]: TxnCoordinator: broker has no address yet: postponing connect
%7|1675710044.011|CONNECT|0105_transactions_mock#producer-56| [thrd:main]: Cluster connection already in progress: acquire ProducerID
[<MAIN>                      /398.102s] 6 thread(s) in use by librdkafka
[<MAIN>                      /398.102s] TEST FAILURE
### Test "<MAIN>" failed at test.c:1596:test_wait_exit() at Mon Feb  6 14:00:44 2023: ###
6 thread(s) still active in librdkafka
test-runner: test.c:6716: test_fail0: Assertion `0' failed.
./run-test.sh: line 62: 726724 Aborted                 $TEST $ARGS
###
###

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v2.0.2`
 - [x] Apache Kafka version: `mock cluster`
 - [x] librdkafka client configuration: `unchanged from original (NULL) `
 - [x] Operating system: `SMP Debian 5.10.162-1 (2023-01-21) x86_64`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by milindl** [comment]
I pushed a fix on master for this, thanks for reporting this.

Let me know if it works for you (The PR is https://github.com/confluentinc/librdkafka/pull/4186).

**Comment by eig** [comment]
This fix completely resolved the problem on both Windows and Linux. Thanks very much. And knowing the reason for the failure gives me a lot more confidence in the results of my build in general. Really appreciate it.

**Comment by milindl** [comment]
Great, closing this.
