### ISSUE TITLE
missing auto.offset.reset in result of dump()

### ISSUE THREAD

**Issue by inPhraZ** [confluentinc/librdkafka#4219]
Description
===========
After setting `auto.offset.reset` to anything, this parameter doesn't show up in result of dump().
also get() only returns either smallest or largest.

How to reproduce
================
```C
if (rd_kafka_conf_set(conf, "auto.offset.reset", "end", errstr,
                      sizeof(errstr)) != RD_KAFKA_CONF_OK) {
        fprintf(stderr, "%s\n", errstr);
        rd_kafka_conf_destroy(conf);
        return 1;
}
if (rd_kafka_conf_get(conf, "auto.offset.reset", dest, &sz) !=
    RD_KAFKA_CONF_OK) {
        fprintf(stderr, "%s\n", errstr);
        rd_kafka_conf_destroy(conf);
        return 1;
}

/*
if auto.offset.reset is one of the values [smallest, earliest, beginning] dest will be smallest.
if auto.offset.reset is one of the values [largest, latest, end] dest will be largest.
*/
printf("get(auto.offset.reset): %s\n", dest);

const char **dump_res = rd_kafka_conf_dump(conf, &cntp);
for (size_t i = 0; i < cntp; i += 2) {
        // auto.offset.reset can't be found in the output
        printf("%s: %s\n", dump_res[i], dump_res[i + 1]);
}
```
Logs (with `debug=conf`) from librdkafka
================
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]: Client configuration:
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]:   client.software.version = 2.0.2-10-g578589-dirty
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]:   metadata.broker.list = localhost:9092
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]:   debug = conf
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]:   default_topic_conf = 0x56101c7d1cd0
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]:   group.id = mygid
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]: Default topic configuration:
%7|1678776101.888|CONF|rdkafka#consumer-1| [thrd:app]:   auto.offset.reset = largest
%7|1678776101.907|CONF|rdkafka#consumer-1| [thrd:main]: Topic "mytopic" configuration (default_topic_conf):
%7|1678776101.907|CONF|rdkafka#consumer-1| [thrd:main]:   auto.offset.reset = largest

Checklist
=========
 - [x] librdkafka version: `v2.0.2-10-g578589-dirty`
 - [x] Apache Kafka version: `confluentinc/cp-*:7.3.0  docker  images`
 - [x] librdkafka client configuration: `same as examples/consumer.c`
 - [x] Operating system: `Ubuntu 22.04.1 LTS (x86_64)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rajatmohan22** [comment]
I feel it is an issue with the version of Kafka. Have you tried updating it?

**Comment by rajatmohan22** [comment]
I might be able to fix this but I am new this whole contributing thing, Could you help me out?

**Comment by nhaq-confluent** [comment]
@inPhraZ has this issue been resolved on your end through a Kafka update?

**Comment by inPhraZ** [comment]
I've upgraded Kafka to kafka_2.13-3.6.1 with librdkafka v2.3.0 , but the issue persists.

**Comment by inPhraZ** [comment]
It became clear to me that `rd_kafka_conf_dump()` will search for the elements of the `rd_kafka_properties` array whose scope is `_RK_GLOBAL`, whereas `auto.offset.reset` is associated with `_RK_TOPIC`. So, I should have used `rd_kafka_topic_conf_dump()` instead.
https://github.com/confluentinc/librdkafka/blob/a6d85bdbc1023b1a5477b8befe516242c3e182f6/src/rdkafka_conf.c#L1616
