### ISSUE TITLE
query_watermark_offsets return low offset equals high offset?

### ISSUE THREAD

**Issue by leonjxchen** [confluentinc/librdkafka#4233]
I'm currently using librdkafka v1.6.2。
when I call query_watermark_offsets with success returns, for some partition, low watermark is equal with high watermark,
the others high watermark is greater than low watermark.
I consumed all of messages in all the partitions.
some logs from my process listed as below
topic partition:[1] offset: 129583 watermark: [low: 129583, high: 129584]
topic partition:[4] offset: 124774 watermark: [low: 124775, high: 124775]
topic partition:[3] offset: 129655 watermark: [low: 129656, high: 129656]
topic partition:[2] offset: 127962 watermark: [low: 127963, high: 127963]
topic partition:[0] offset: 128303 watermark: [low: 128303, high: 128304]

can anybody tell me when low watermark will equals with wigh watermark?
I did call query_watermark_offsets for an empty topic which returns low = 0 and high = 1

Does this have any relation to offsets retention?

one possible way I could think of is, consumer group commited offset in broker expired, broker 
knows nothing about this consumer group, when this consumer group consumed some messages from 
some partition but not all of partition. and then consumer group commit offsets to broker, for 
those partition without new message produced, low watermark will equals with high watermark.

By the way, I do manually offset commit

**Comment by emasab** [comment]
As @rajatmohan22 said that is a normal situation if messages have been deleted by retention time. If you have committed offset that were deleted by the retention policy, an offset reset will be made, to latest by default.

Set it to earliest if you want to process all the messages, but in this case they had been already deleted.
