### ISSUE TITLE
BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: No error) .. while connecting to Kafka server in python using confluent_kafka

### ISSUE THREAD

**Issue by balubinnu** [confluentinc/librdkafka#4287]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
Please send more information about this issue. That error code can be normal

**Comment by balubinnu** [comment]
Not able to establish the connection with Kafka server (running on External server).
Please find the program : 
from confluent_kafka import Consumer, KafkaError
from confluent_kafka import Producer, KafkaError
 
#c = Consumer({
#  'bootstrap.servers': 'kafka-0.broker.emh-sit.service.dev:443',
#  'group.id': 'test-account-event-bgm-consumer',
#  'security.protocol':'SASL_SSL',
#  'sasl.mechanisms':'GSSAPI',
#  'ssl.ca.location': 'Cert\\kafkacert.pem',
#  'ssl.certificate.location':'Cert\\trustcert.pem'
#
#})
topic='au.mps.test.event.account'
data = {"header": {"eventUUID": "4f0045a8-6684-7035-d7e6-0559b842ba7f", "productCode": "CAP-CIS:CAP", "subject": {"subjectType": "CAP-CIS", "subjectId": "00000000000000185146806"}, "source": "OCV", "occurrenceDateTime": 339668094173, "traceId": "767798312290", "spanId": "223356634704", "parentSpanId": "223356634704", "correlationId": 339668094173, "hierarchy": "GLOBAL/DATA/OCV", "ignore": False, "eventType": "Account Deleted", "expiryDateTime": "Null"}, "OcvTags": "Null", "eventData": {"performedAction": "delete", "lastUpdatedDate": "2023-14-01 15:14:40.0", "lastUpdatedBy": "INT", "version": 0, "accountOpenedDate": "2023-14-01 15:14:40.0", "accountClosedDate": "2023-14-01 15:14:40.0", "accountBranchNumber": "3128", "accountStatus": "Null", "accountStatusRaw": "Null", "accountNameOne": "A TEST", "accountNameTwo": "Null", "accountNameThree": "Null", "accountShortName": "Null", "accountSubProduct": "CAP-CIS:CAP309", "accountCurrency": "Null", "accountSource": "CAP-CIS", "companyId": "10", "marketingCode": "Null", "numberOfSignatures": "Null", "regulatedIndicator": "Null", "atomicAttributes": "Null", "addresses": "Null", "linkedAccounts": "Null"}}
conf = {'bootstrap.servers': 'server_ip',
        'security.protocol':'SASL_SSL',
        'sasl.mechanisms':'GSSAPI',
		'api.version.request':True,
		'ssl.ca.location':'trustcert.pem',
		'ssl.certificate.location':'kafkacert.pem',
		'ssl.key.location':'kafkakey.pem',
		'ssl.key.password':'changeit',
        'enable.ssl.certificate.verification':True,
		'debug':'broker,admin,protocol'}
prod = Producer(conf)

**Comment by emasab** [comment]
That error is returned in the AdminClient when librdkafka handle is terminating, to inform async operation cannot be completed. Please provide complete example code for reproducing it.
