### ISSUE TITLE
Segfaults during consumer shutdown

### ISSUE THREAD

**Issue by vwassan** [confluentinc/librdkafka#4308]
Description

References the assert fail [here](https://github.com/confluentinc/librdkafka/blob/4b63c6c8881968f7185da33f09cbd69561bb612c/src/rdkafka_sticky_assignor.c#L1902)

Stacktrace 👇 

```
#13 0x00007f91d047771b in __assert_fail_base
    (fmt=0x7f91d062c150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f91b1bac69d "assignor_state", file=0x7f91b1bac668 "rdkafka_sticky_assignor.c", line=1896, function=<optimized out>) at ./assert/assert.c:92
#14 0x00007f91d0488e96 in __GI___assert_fail
    (assertion=assertion@entry=0x7f91b1bac69d "assignor_state", file=file@entry=0x7f91b1bac668 "rdkafka_sticky_assignor.c", line=line@entry=1896, function=function@entry=0x7f91b1bad2e0 <__PRETTY_FUNCTION__.3> "rd_kafka_sticky_assignor_state_destroy") at ./assert/assert.c:101
#15 0x00007f91b1ae950d in rd_kafka_sticky_assignor_state_destroy (assignor_state=0x0) at rdkafka_sticky_assignor.c:1896

```
How to reproduce

Not sure about the exact steps, but we are noticing this during consumer shutdown flow.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): We are using [rdkafka-ruby](https://github.com/appsignal/rdkafka-ruby) version `0.13.0.beta.6`, which relies on [librdkafka version 1.9.2](https://github.com/appsignal/rdkafka-ruby/blob/main/CHANGELOG.md).
 - [x] Apache Kafka version: `<3.4.0>`
 - [x] librdkafka client configuration: `<auto.reset.offset=earliest, majority of the configs are set to default values>`
 - [x] Operating system: `<Ubuntu 22.04.2 LTS>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Critical issue

**Comment by mensfeld** [comment]
I opened it for investigation on our side: https://github.com/appsignal/rdkafka-ruby/issues/254

**Comment by mensfeld** [comment]
And I have a full reproduction setup. In the upcoming days I will see if this can be fixed on our side or if we need some extra help.

**Comment by nhaq-confluent** [comment]
@mensfeld @vwassan based on the conversation I am closing this issue. Thanks!

**Comment by mensfeld** [comment]
@nhaq-confluent yes. It is no longer an issue. Things are super stable now.
