### ISSUE TITLE
Memory Usage of Producer Keep Increase after update Kafka Client (2.0.2) and Apache Kafka Server (3.0.3)

### ISSUE THREAD

**Issue by roygao2017** [confluentinc/librdkafka#4313]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
We recently upgraded the Kafka broker to version 3.3 and recompiled the Producer using librdkafka 2.0.2 to support the new version. However, we found that the memory kept increasing on some machines. 
We used Valgrind to locate the issue and did not find many deterministic leaks, but found many reachable memory usage related to Librdkafka. The size of reachable memory matches the memory growth.

from the valgrind, i can see more memory related with librdkafka and openssl (OpenSSL 1.0.2k-fips), even they are reachable, but looks like were blocked there.

Therefore, I suspect that some configurations or dependent libraries need to be updated, or impacted by security, which may have caused a decrease in performance or delayed memory release.

I would greatly appreciate it if you could help me.

part of code:
produce_xxx_msg():
i_ret = add_or_query_schema ( pst_topic, &value );
i_ret = compose_gtp_message(&value, pst__msg);

serdes_schema_serialize_avro();

i_ret = rd_kafka_produce ( rkt, partition,
                                   RD_KAFKA_MSG_F_COPY,
                                   ser_buf, 
                                   ser_buf_size,
                                   NULL, 0,
                                   NULL );

if (success _iret)
{ 
     cnt++
    if (cnt>10000)
    {
                rd_kafka_poll ( rk, 0/*non-blocking*/ );
                cnt= 0;
                msg_cnt = rd_kafka_outq_len(rk);
                log(msg_cnt);
    }
   free ( ser_buf );
   avro_value_decref ( value );
}
else
{
    log_err();
    rd_kafka_poll ( rk, 50);
    backup_data();
    free ( ser_buf );
    avro_value_decref ( value );
}

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the 
following information:

 - [x] librdkafka version (release number or git tag): `<2.0.2>`
 - [ ] Apache Kafka version: `<3.3>`
 - [ ] librdkafka client configuration: `<compression.codec = snappy
queue.buffering.max.messages = 100000
queue.buffering.max.ms = 5000
batch.num.messages = 10000
message.send.max.retries = 2

security.protocol = SASL_SSL
ssl.certificate.location = /etc/TrustedRoot.crt
ssl.key.password = changeit
ssl.keystore.password = changeit
log.connection.close = false

sasl.kerberos.keytab=/etc/conprdops.keytab
sasl.kerberos.principal=XXX
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=kafka
socket.keepalive.enable=true.>`
 - [ ] Operating system: `<RHEL 7.9  3.10.0-1160.71.1.el7.x86_64>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

[valgrind.txt](https://github.com/confluentinc/librdkafka/files/11712164/valgrind.txt)

**Comment by roygao2017** [comment]
it's not caused by client. we have found the reason. thank you.

**Comment by manhtd98** [comment]
> it's not caused by client. we have found the reason. thank you.

I have the same problem. What's your root resean?
