### ISSUE TITLE
Possible Bug with consuming from Partition Queues during leader elections

### ISSUE THREAD

**Issue by wmorgan6796** [confluentinc/librdkafka#4340]
Description
===========
Our team has noticed a peculiar bug that happens with our consumer:

We do the following with our consumer when we rebalance:

`std::unique_ptr<RdKafka::Queue> partition_queue(consumer_->get_partition_queue(topic_partition));`

To get the partition queue for each partition we're consuming. We then make it so we don't have that queue forwarding at all (so we can consume from that queue directly (each partition getting its own thread to consume it). 

The behavior we've seen is that in the face of the cluster undergoing a leader election, where the leader for a partition we're consuming changes, the `partition_queue` will cease to receive anymore messages after the leader election occurs sometimes.

I'm not sure if its a bug or if its working as expected, but if a leader election occurs, and the partition we're consuming now gets served from a different broker, is it expected that we will continue to receive messages on that partition queue or are we expected to continually grab a new queue? I think it should just be fine to consume the partition queue, as it seems to work most of the time, but not all the time.

How to reproduce
================

1. Be consuming at a high rate with a large cluster on a single topic with a high number of partitions (> 800 partitions).
2. Grab the partition queue for the `TopicPartition` you're consuming and set the forwarding to a nullptr
3. Consume messages from the queue.
4. Have a leader election occur for the Partition that you're consuming where the replica for the partition is out of sync with the leader, but `unclean.leader.election.enable=false` is set. So our consumption gets paused until the leader comes back online. (at least as best I understand it)
5. Notice that the messages you're receiving from the queue drops to 0.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 2.1.1
 - [x] Apache Kafka version: 2.8.1
 - [x] librdkafka client configuration:
```
===== Global Kafka Consumer Config =====

        allow.auto.create.topics = false
        api.version.fallback.ms = 0
        api.version.request = true
        api.version.request.timeout.ms = 10000
        auto.commit.interval.ms = 5000
        batch.num.messages = 10000
        batch.size = 1000000
        broker.address.family = any
        broker.address.ttl = 1000
        broker.version.fallback = 0.10.0
        builtin.features = gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,zstd,sasl_oauthbearer
        check.crcs = false
        client.id = liveness.consumer
        client.rack = scl2
        client.software.name = librdkafka
        compression.codec = none
        connections.max.idle.ms = 0
        coordinator.query.interval.ms = 600000
        debug =
        default_topic_conf = 0x7f7f42e08600
        delivery.report.only.error = false
        enable.auto.commit = false
        enable.auto.offset.store = false
        enable.gapless.guarantee = false
        enable.idempotence = false
        enable.partition.eof = false
        enable.random.seed = true
        enable.sasl.oauthbearer.unsecure.jwt = false
        enable.sparse.connections = true
        enable.ssl.certificate.verification = true
        enable_sasl_queue = false
        enabled_events = 0
        fetch.error.backoff.ms = 500
        fetch.max.bytes = 52428800
        fetch.message.max.bytes = 1048576
        fetch.min.bytes = 1
        fetch.wait.max.ms = 500
        group.id = <REDACTED>
        group.instance.id = <REDACTED>
        group.protocol.type = consumer
        heartbeat.interval.ms = 3000
        internal.termination.signal = 0
        isolation.level = read_committed
        log.connection.close = true
        log.queue = false
        log.thread.name = true
        log_cb = 0x13a2ee0
        log_level = 6
        max.in.flight.requests.per.connection = 1000000
        max.poll.interval.ms = 300000
        message.copy.max.bytes = 65535
        message.max.bytes = 1000000
        message.send.max.retries = 2147483647
        metadata.broker.list = <REDACTED>
        metadata.max.age.ms = 900000
        metadata.request.timeout.ms = 10
        offset.store.method = broker
        open_cb = 0x1402730
        partition.assignment.strategy = range,roundrobin
        queue.buffering.backpressure.threshold = 1
        queue.buffering.max.kbytes = 1048576
        queue.buffering.max.messages = 100000
        queue.buffering.max.ms = 5
        queued.max.messages.kbytes = 65536
        queued.min.messages = 100000
        receive.message.max.bytes = 100000000
        reconnect.backoff.jitter.ms = 0
        reconnect.backoff.max.ms = 10000
        reconnect.backoff.ms = 100
        retry.backoff.ms = 100
        sasl.kerberos.kinit.cmd = kinit -R -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal} || kinit -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal}
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.principal = kafkaclient
        sasl.kerberos.service.name = kafka
        sasl.mechanisms = GSSAPI
        sasl.oauthbearer.method = default
        security.protocol = plaintext
        session.timeout.ms = 90000
        socket.blocking.max.ms = 1000
        socket.connection.setup.timeout.ms = 30000
        socket.keepalive.enable = false
        socket.max.fails = 1
        socket.nagle.disable = false
        socket.receive.buffer.bytes = 0
        socket.send.buffer.bytes = 0
        socket.timeout.ms = 60000
        socket_cb = 0x13bde20
        ssl.ca.certificate.stores = Root
        ssl.endpoint.identification.algorithm = https
        ssl.engine.id = dynamic
        statistics.interval.ms = 300000
        sticky.partitioning.linger.ms = 10
        test.mock.broker.rtt = 0
        test.mock.num.brokers = 0
        topic.metadata.propagation.max.ms = 30000
        topic.metadata.refresh.fast.cnt = 10
        topic.metadata.refresh.fast.interval.ms = 250
        topic.metadata.refresh.interval.ms = 300000
        topic.metadata.refresh.sparse = true
        transaction.timeout.ms = 60000
2023-06-29T18:50:16.740636Z csm-liveness: [INFO] consumer.cpp:115 -
===== Topic Kafka Consumer Config =====

        auto.commit.enable = true
        auto.commit.interval.ms = 60000
        auto.offset.reset = largest
        compression.codec = inherit
        compression.level = -1
        consume.callback.max.messages = 0
        message.timeout.ms = 300000
        offset.store.method = broker
        offset.store.path = .
        offset.store.sync.interval.ms = -1
        partitioner = consistent_random
        produce.offset.report = false
        queuing.strategy = fifo
        request.required.acks = -1
        request.timeout.ms = 30000
```
 - [x] Operating system: Ubuntu 20.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka --> Haven't been able to grab logs as of yet
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
Hello @wmorgan6796 I have a doubt about this comment:

> Have a leader election occur for the Partition that you're consuming where the replica for the partition is out of sync with the leader, but unclean.leader.election.enable=false is set. So our consumption gets paused until the leader comes back online. (at least as best I understand it)

So when the old leader comes back online does your consumption restart? If that's the case this is the expected behavior as a new leader can only be elected among the ISR set and if only one is left, without unclean leader election, that'll stay the leader and it 'll be unavailable.

After you restart the old leader, does it continue being the leader or does the other broker becomes in-sync an is elected new leader?

**Comment by wmorgan6796** [comment]
hi @emasab, sorry for the delayed response, been busy hunting down this problem.

So I believe we've found the problem, namely its a fun bug with Kafka itself and how Librdkafka reacts. In short, our team believes to have found a bug within Kafka 2.8.1 where if the broker loses access to Zookeeper for a minute or so and then zookeeper comes back, the broker struggles to get the new leader epoch from zookeeper to the point where the epoch it gets for a few of the partitions it owns are invalid and requires that the broker itself be restarted to recover (occasionally this bug will actually bring down an entire cluster as well).

When this error occurs, Librdkafka reacts as we would expect:

1. First we see a leadership change from one broker to another for a partition
```
2023-08-15T04:30:23.436755Z [TOPICUPD][thrd:main]: Topic <REDACTED> [220]: migrating from broker 14810870 to 14410619 (leader is 14410619): leader updated
```
2. We then query the new leader for the epoch validation of an offset
```
2023-08-15T04:30:23.436790Z [VALIDATE][thrd:main]: <REDACTED>/14410619: <REDACTED> [220]: querying broker for epoch validation of offset 67950578381 (leader epoch 48): epoch updated from metadata
```
3. We also wee that the the current partition is not fetchable from the old leader anymore and remove the fetching for that partition from that broker
```
2023-08-15T04:30:23.439982Z [FETCH][thrd:<REDACTED>:9092/bootstrap]: <REDACTED>:9092/14810870: Topic <REDACTED> [220] in state validate-epoch-wait at offset 66922542623 (leader epoch -1) (0/100000 msgs, 0/65536 kb queued, opv 82) is not fetchable: forced removal
```
5. We then attempt to validate the epoch for a the partition for the given offset
```
2023-08-15T04:30:23.441478Z [VALIDATE][thrd:main]: <REDACTED>:9092/14410619: <REDACTED> [220]: querying broker for epoch validation of offset 67950578381 (leader epoch 48): epoch updated from metadata
```
7. We get the error saying the Leader epoch is newer than the broker epoch (because the broker which is the leader is unable to fetch the latest epoch from zookeeper due to the bug in Kafka 2.8.1 (and we believe a bug on the latest main of kafka).
```
2023-08-15T04:30:23.451293Z [OFFSETVALID][thrd:main]: <REDACTED>:9092/14410619: <REDACTED> [220]: OffsetForLeaderEpoch requested failed: Broker: Leader epoch is newer than broker epoch
```

Librdkafka then will continue in a loop of fetching metadata and seeing that the broker has an invalid epoch, essentially pausing consumption of that partition especially since the leader has an invalid epoch, it seems like it won't transition to the follower either for consumption.

We've even seen afterwards that we continue to see paused consumption for that partition even after the broker was restarted, and continue to be paused until we force a rebalance of the consumer group, usually by restarting a consumer or 2.

I'm not sure what we can do here, but it seems like Librdkafka struggles to recover in the face of this failure without requiring a rebalance. The reason this originally manifested as something we saw during Leader elections is that we believe it happens due to the zookeeper <--> Broker network partition that occurs.

Any ideas or help on how to mitigate this would be helpful. We think theres a bug around the fact that we continue to not be able to consume that partition until a rebalance occurs, even after the issue inside the brokers is fixed.

**Comment by emasab** [comment]
@wmorgan6796 thanks for the details. Please attach new leader logs when it couldn't transition to the new leader epoch or link to the AK issue you file. It seems metadata response was continuing returning that broker as leader for the partition between one retry and the next one.

**Comment by wmorgan6796** [comment]
I’ll see what I can do. Our team who run’s Kafka is currently looking more closely into the issue. We’re unsure if it’s been patched in Kafka 3.5 (which is what we’re moving to from 2.8.1) in addition to upgrading zookeeper. The restrictions on releasing logs to external folks are quite high, so I may not be able to provide the leadership logs. Hopefully upgrading should fix it, but unfortunately that’s a long tail for us as there are thousands of brokers that need to get upgraded.

**Comment by wmorgan6796** [comment]
It seems like we've figure this out internally with our data platform team. I'll be closing the issue as its no longer a problem for us.

Thanks for the responses.

**Comment by qrpike** [comment]
@wmorgan6796 any details you can give on what the issue/fix was would be helpful to the community. Thanks!

**Comment by wmorgan6796** [comment]
The issue was a bug in Kafka’s zookeeper code for the version we were on (2.8.1) at the time. If the network has a blip there’s a chance that the controller of the cluster could get an invalid epoch causing things to break down and act weird. Since we’ve figured this out, we’ve found that upgrading  to Kafka 3.6.1 fixed this.
