### ISSUE TITLE
Error while Consuming kafka topic

### ISSUE THREAD

**Issue by Nixia408** [confluentinc/librdkafka#4344]
Description:

We are intermittently getting following error while consuming kakfa atopic

rdkafka_queue.h:194:rd_kafka_q_destroy0: assert: rkq->rkq_refcnt > 0 
Once we get above error the application crashes.
there some log like this:
kafka_logError: Offset commit of 1 partition(s): Local: Timed out

We find the corresponding code is：
	/* Clear queues */
	rd_kafka_assert(rktp->rktp_rkt->rkt_rk,
			rd_kafka_msgq_len(&rktp->rktp_xmit_msgq) == 0);

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (v0.11.5.)

**Comment by mensfeld** [comment]
v0.11.5 was released in Jul 19, 2018. That is 5 years ago. I would advice you upgrading first.

**Comment by emasab** [comment]
Thanks @mensfeld . Yes, Confluent supports versions >= 1.6.0
https://docs.confluent.io/platform/current/clients/index.html#librdkafka-and-derived-clients
