### ISSUE TITLE
How to recompile librdkafka with openssl support?

### ISSUE THREAD

**Issue by yochai-g** [confluentinc/librdkafka#4355]
We are moving now from OpenSSL 1.1.1 to OpenSSL 3.

I built librdkafka running the following commands:

**./configure --enable-ssl --enable-zlib --disable-zstd --disable-shared --includedir=${BUILD_ROOT}/adi.headers/include --libdir=${ADI_OPENSSL_ROOT}/lib
make libs**

But when we are trying to connect, we got:

**No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM OAUTHBEARER**

How can I configure the librdkafka to use OpenSSL ?

**Comment by emasab** [comment]
Hello @yochai-g , the error you're getting isn't caused by OpenSSL but because of the default `sasl.mechanism` that is `GSSAPI` (Kerberos). If you want to connect to Confluent Cloud set `sasl.mechanism` to `PLAIN` along with `sasl.username` and `sasl.password`.

**Comment by yochai-g** [comment]
Hi,
Thanks for your answer.
We want to use OpenSSL 3.1 to connect. 
My question is how to build librdkafka to use OpenSSL ?

**Comment by emasab** [comment]
You need GSSAPI (libsasl2-dev package) if you need to use Kerberos. If you need only SSL you just need to set sasl.mechanism to a different value depending on the authentication mechanism you need. Also if you don't need Kerberos and you're using Py, .NET or Go clients, you don't need to recompile librdkafka as there are prebuilt binaries included with OpenSSL 3 for many platforms.
