### ISSUE TITLE
Manual offset incrementation/auto commiting stopped working on Azure eventhub since version 2.1.0

### ISSUE THREAD

**Issue by pbizon** [confluentinc/librdkafka#4384]
Read the FAQ first: https://github.com/confluentinc/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/confluentinc/librdkafka/discussions

Description
===========
Changes introduced in this PR:
https://github.com/confluentinc/librdkafka/commit/a0871a1a8ff435a9342f1a60dca4c696a54c7ae2#diff-14f07c2626b2863a69e4b9b625720d25a860298da6d8f3dd81289b617ad7a9b5
cause that before setting a new offset in `rd_kafka_topic_partition_list_set_offsets` we compare not only offsets but also `leader_epochs`.

```
    if (rd_kafka_fetch_pos_cmp(&rktp->rktp_stored_pos,
                                &rktp->rktp_committed_pos) >
        0) {
        ...
        }
```
```
rd_kafka_fetch_pos_cmp(const rd_kafka_fetch_pos_t *a,
                       const rd_kafka_fetch_pos_t *b) {
        if (a->leader_epoch < b->leader_epoch)
                return -1;
        else if (a->leader_epoch > b->leader_epoch)
                return 1;
        else if (a->offset < b->offset)
                return -1;
        else if (a->offset > b->offset)
                return 1;
        else
                return 0;
}
```
Everything works fine with Apache Kafka implementation which send `-1` as leaderEpoch in `OffsetFetchResponse`.
```
{"severity":7,"fac":"OFFSETFETCH","message":"[thrd:main]: GroupCoordinator/1: OffsetFetchResponse: test-topic [0] offset 1, leader epoch -1, metadata 0 byte(s): NO_ERROR"}
```
Unfortunatelly Azure eventhub sends `0`.
```
{"severity":7,"fac":"OFFSETFETCH","message":"[thrd:main]: GroupCoordinator/0: OffsetFetchResponse: test-topic [0] offset -1, leader epoch 0, metadata 0 byte(s): NO_ERROR"}
[KAFKA] {"severity":7,"fac":"OFFSET","message":"[thrd:main]: Topic test-topic [2]: stored offset 316172 (leader epoch -1), committed offset INVALID (leader epoch 0): not including in commit"}
[KAFKA] {"severity":7,"fac":"OFFSET","message":"[thrd:main]: Topic test-topic [3]: stored offset 318224 (leader epoch -1), committed offset 318180 (leader epoch 0): not including in commit"}
```
And now when the timer expires even though `new_offset > old_offset` unfortunately `new_leader_epoch < old_leader_epoch` (-1 < 0) and we are not committing this offset.

I didn't find anything about default value for leader_offset in this document: https://cwiki.apache.org/confluence/display/KAFKA/KIP-320%3A+Allow+fetchers+to+detect+and+handle+log+truncation so I'm assuming that 0 is a valid value.

How to reproduce
================
Connect consumer to the topic of Azure eventhub with these configuration parameters:
  'enable.auto.commit': true,
  'auto.commit.interval.ms': 5000,
  'enable.auto.offset.store': false,
  offset_commit_cb: [Function: offset_commit_cb]

Increment offset manually in your consumer.

Send something to the test topic and observe whether offset_commit_cb has been called or not.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/confluentinc/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `since v2.1.0`
 - [x] Apache Kafka version: `Azure Eventhub`
 - [x] librdkafka client configuration: `'client.id': '$ConnectionString',
  'group.id': 'kafka-consumer-1',
  'metadata.broker.list': '[redacted].windows.net:9093',
  'topic.metadata.refresh.interval.ms': 60000,
  'metadata.max.age.ms': 180000,
  'session.timeout.ms': 30000,
  'sasl.mechanisms': 'PLAIN',
  'sasl.username': '$ConnectionString',
  'sasl.password': [redacted],
  'security.protocol': 'SASL_SSL',
  'ssl.ca.location': '/etc/ssl/certs',
  'socket.keepalive.enable': true,
  'enable.auto.commit': true,
  'auto.commit.interval.ms': 5000,
  'enable.auto.offset.store': false,
  debug: 'broker,consumer,msg,topic',
  offset_commit_cb: [Function: offset_commit_cb]
`
 - [x] Operating system: `Linux`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
Hello @pbizon . A value of -1 as offset leader epoch is the correct one when returning an offset of -1, as it corresponds to NULL. You can try filing a bug to Azure eventhub.
As a workaround you can store your offsets with a leader epoch that corresponds to the leader epoch of the stored offset (0 in this case), by using rd_kafka_topic_partition_set_leader_epoch

**Comment by pbizon** [comment]
Hi,
Thanks for your response.
I don't quite understand why with the same broker library is able to commit offset when auto.offset.store is enabled:
```
[KAFKA] {"severity":7,"fac":"OFFSET","message":"[thrd:main]: Topic inbound.000001 [0]: stored offset 319373 (leader epoch 0), committed offset 319223 (leader epoch 0): setting stored offset 319373 (leader epoch 0)  for commit"}
[KAFKA] {"severity":7,"fac":"OFFSET","message":"[thrd:main]: Topic inbound.000001 [1]: stored offset 320929 (leader epoch 0), committed offset 320764 (leader epoch 0): setting stored offset 320929 (leader epoch 0)  for commit"}
[KAFKA] {"severity":7,"fac":"OFFSET","message":"[thrd:main]: Topic inbound.000001 [2]: stored offset 319474 (leader epoch 0), committed offset 319304 (leader epoch 0): setting stored offset 319474 (leader epoch 0)  for commit"}
[KAFKA] {"severity":7,"fac":"OFFSET","message":"[thrd:main]: Topic inbound.000001 [3]: stored offset 321360 (leader epoch 0), committed offset 321356 (leader epoch 0): setting stored offset 321360 (leader epoch 0)  for commit"}
```

**Comment by emasab** [comment]
Hi @pbizon. for storing offsets, are you using rd_kafka_offset_store or rd_kafka_offsets_store?

**Comment by pbizon** [comment]
Hi @emasab,
Since I'm using node-rdkafka, there is only KafkaConsumer::offsets_store binding available.

**Comment by emasab** [comment]
What are you storing, the message directly or creating a TopicPartitionOffset?

**Comment by pbizon** [comment]
As far as I understand the TopicPartitionOffset is created:
```
  std::vector<RdKafka::TopicPartition *> toppars =
    Conversion::TopicPartition::FromV8Array(info[0].As<v8::Array>());

  Baton b = consumer->OffsetsStore(toppars);
```
where from js it gets:
```
const offset = [
  {
    topic: message.topic,
    partition: message.partition,
    offset: message.offset + 1
  }
]
stream.consumer.offsetsStore(offset)
```

**Comment by pantoss-torstone** [comment]
I've been looking at the problem which @kostasdizas has been having and I think I see the problem.  @emasab are you able to confirm that my thinking is correct?

inside rd_kafka_msgset_reader_msg_v2 it handles control messages first and creates  ctrl msg ops with the current offset.

`                rko = rd_kafka_op_new_ctrl_msg(rktp, msetr->msetr_tver->version,
                                               rkbuf, hdr.Offset);
                rd_kafka_q_enq(&msetr->msetr_rkq, rko);
                msetr->msetr_msgcnt++;

                return RD_KAFKA_RESP_ERR_NO_ERROR;
        }`

you will notice that rd_kafka_op_new_ctrl_msg doesn't have the leader epoch passed into it. rd_kafka_op_new_ctrl_msg calls  rd_kafka_op_new_fetch_msg to create a new op. Below this point the code handle the messages where is calls rd_kafka_op_new_fetch_msg just like rd_kafka_op_new_ctrl_msg however the next line it sets the leader_epoch.

`        /* Create op/message container for message. */
        rko = rd_kafka_op_new_fetch_msg(
            &rkm, rktp, msetr->msetr_tver->version, rkbuf, hdr.Offset,
            (size_t)RD_KAFKAP_BYTES_LEN(&hdr.Key),
            RD_KAFKAP_BYTES_IS_NULL(&hdr.Key) ? NULL : hdr.Key.data,
            (size_t)RD_KAFKAP_BYTES_LEN(&hdr.Value),
            RD_KAFKAP_BYTES_IS_NULL(&hdr.Value) ? NULL : hdr.Value.data);

        rkm->rkm_u.consumer.leader_epoch = msetr->msetr_leader_epoch;
        rkm->rkm_broker_id               = msetr->msetr_broker_id;`

 @emasab added this additional line but it wasn't added to the the control messages.
 
 Inside rd_kafka_q_serve_rkmessages we see that although it discards the ctrl msgs it does still try and read and store the epoch.
`        /* Discard ctrl msgs */
        next = TAILQ_FIRST(&ctrl_msg_q);
        while (next) {
                rko                     = next;
                next                    = TAILQ_NEXT(next, rko_link);
                rd_kafka_toppar_t *rktp = rko->rko_rktp;
                int64_t offset = rko->rko_u.fetch.rkm.rkm_rkmessage.offset + 1;
                if (rktp && (rktp->rktp_app_pos.offset < offset))
                        rd_kafka_update_app_pos(
                            rk, rktp,
                            RD_KAFKA_FETCH_POS(
                                offset,
                                rd_kafka_message_leader_epoch(
                                    &rko->rko_u.fetch.rkm.rkm_rkmessage)),
                            RD_DO_LOCK);
                rd_kafka_op_destroy(rko);
        }
`

**Comment by pantoss-torstone** [comment]
@pbizon Are you using kafka transactions by any chance but that might explain why you are seeing the epoch of 0 rather then -1.

@emasab I've just jumped into the middle of this code and so my assertions could be completely wrong. Would it make sense to change the interface to rd_kafka_op_new_fetch_msg so that it required you to pass the epoch in during construction? This would force all locations to be updated correctly.

**Comment by emasab** [comment]
@pantoss-torstone Good spot, thanks! Control message leader epochs must be set as well

**Comment by emasab** [comment]
Fixed by the two merged commits
