### ISSUE TITLE
max.poll.interval.ms is not reset while using consume_cb

### ISSUE THREAD

**Issue by milindl** [confluentinc/librdkafka#4421]
Illustrative code to reproduce,

```C
        // Set max.poll.interval.ms and session.timeout.ms to 10000
        rd_kafka_conf_set_consume_cb(conf, consume_cb);
        rk = rd_kafka_new(RD_KAFKA_CONSUMER, conf, errstr, sizeof(errstr));
        rd_kafka_poll_set_consumer(rk);
        rd_kafka_subscribe(rk, subscription);
        while (1) { rd_kafka_poll(rk, 1000); } /* wait 10 s */
```

Why does it happen? 

We have the check, `can_q_contain_fetched_msgs`, which checks if `rk->rk_rep` can contain consumer messages. We've done this since `rk_rep` is passed to the argument inside `rd_kafka_q_serve`, so we only check that queue. However, internally, `rd_kafka_q_serve` checks if its argument queue is forwarded to any other queue (`fwdq`), and calls `rd_kafka_q_serve` on the  `fwdq`. 

In this case, `fwdq` is the `rkcg_q` which does contain consumer messages. 

A possible solution is to move the check `can_q_contain_fetched_msgs` inside `rd_kafka_q_serve`. That way, the `fwdq` will also be checked.

Also affects `rd_kafka_queue_poll`, `rd_kafka_queue_poll_callback`.

**Comment by emasab** [comment]
A workaround is to use directly the queue it's forwarded to: 
`rd_kafka_queue_poll_callback(rd_kafka_queue_get_consumer(rk), timeout);`

Currently a queue contains messages if it contains messages on its own or a queue containing messages is forwarded to it.

We have to add that it also contains messages if does contain natively, but it's forwarded to a queue containing messages. By putting that check after forwards in rd_kafka_q_serve is an option.
