### ISSUE TITLE
Update OpenSSL version to the latest release (3.0.8 has known vulnerabilities)

### ISSUE THREAD

**Issue by ayende** [confluentinc/librdkafka#4428]
Description
===========
Similar to this: https://github.com/confluentinc/librdkafka/pull/4215

Version 3.0.8 of OpenSSL has known vulnerabilities, is it possible to upgrade to the latest released version?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `2.2.0`
 - [x] Apache Kafka version: `not relevant, client side only`
 - [x] librdkafka client configuration: `not relevant, issue is with the distributed dll`
 - [x] Operating system: `Windows, etc`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: N/A
 - [x] Provide broker log excerpts: N/A
 - [x] Critical issue: We got concerns from our users about this, so important, but not critical.

**Comment by emasab** [comment]
Fixed with https://github.com/confluentinc/librdkafka/pull/4454 . We're currently staying with LTS 3.0 branch.

**Comment by ppekrol** [comment]
Thanks, do you know when next release is planned +/- ?
