### ISSUE TITLE
How can I configure c# apache kafka Producer client with sasl.login.callback.handler.class?

### ISSUE THREAD

**Issue by lavita1206** [confluentinc/librdkafka#4517]
Read the FAQ first: https://github.com/confluentinc/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/confluentinc/librdkafka/discussions

Description
===========
I want to use OAuth in apache kafka with C# client. How can I configure C# apache kafka Producer client with sasl.login.callback.handler.class? Thanks a lot!

I can't find any config which allow me to set sasl.login.callback.handler.class.

I need to set like this:
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler

Here is my config, but it not work because it lack sasl.login.callback.handler.class.

                private ProducerConfig _config = new ProducerConfig();
                _config.BootstrapServers = server;
                _config.ClientId = clientId;
                _config.SecurityProtocol = SecurityProtocol.SaslPlaintext;
                _config.SaslMechanism = SaslMechanism.OAuthBearer;
                _config.SaslOauthbearerClientId = SaslOauthbearerClientId;
                _config.SaslOauthbearerClientSecret = SaslOauthbearerClientSecret;
                _config.SaslOauthbearerScope = SaslOauthbearerScope;
                _config.SaslOauthbearerTokenEndpointUrl = tokenurl;

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/confluentinc/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emasab** [comment]
It seems you're using the property `sasl.oauthbearer.token.endpoint.url` that is required when you're using method OIDC, so you should also set
`SaslOauthbearerMethod = SaslOauthbearerMethod.Oidc`
no handler is required in that case.
