### ISSUE TITLE
Hang if incremental assign is received while consumer is closing

### ISSUE THREAD

**Issue by emasab** [confluentinc/librdkafka#4527]
Description
===========
Consumer in cooperative incremental mode will hang if an assignment callback is being processed while it's closing.

How to reproduce
================
Added a variation 3 to test 0113 to reproduce the bug. The test times out.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `master`
 - [x] Apache Kafka version: `any`
 - [x] librdkafka client configuration: `any`
 - [x] Operating system: `any`
 - [ ] Critical issue

**Comment by mensfeld** [comment]
@emasab I think this works:
1. unsubscribe
2. wait so there are no assignments
3. close

With this I was not able to hang it.

**Comment by nhaq-confluent** [comment]
@emasab could this issue be closed or should it remain open?

**Comment by emasab** [comment]
@nhaq-confluent what @mensfeld proposed is a workaround, but we have to review and merge this PR I created
https://github.com/confluentinc/librdkafka/pull/4528
