### ISSUE TITLE
Offset cannot be set for KafkaConsumer

### ISSUE THREAD

**Issue by ZelinMa557** [confluentinc/librdkafka#4551]
Description
===========
<your issue description goes here>
I found that if I create a TopicPartition, and set its offset, the consumer still consume from the latest offset. I read from FAQ, it say "This API is deprecated but there is no plan to remove it, please see the rd_kafka_assign() or KafkaConsumer::assign() API for a more modern alternative." , but actually those API doesn't work as the same as Simple Consumer.

How to reproduce
================
Example cpp code:
```cpp
RdKafka::TopicPartition* partition = RdKafka::TopicPartition::create(topic, partition, offset);
std::vector<RdKafka::TopicPartition*> partitions{partition};
consumer_->assign(partitions);
auto msg = consumer_->consume(timeout_ms);
std::cout<<msg->offset()<<std::endl;
```
So how can I set offset for KafkaConsumer, or will there be any fix? I found a wiki https://github.com/confluentinc/librdkafka/wiki/Manually-setting-the-consumer-start-offset, but it dos not work now.  

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v2.3.0-RC4  git sha: 95a542c87c61d2c45b445f91c73dd5442eb04f3c
 - [ ] Apache Kafka version: 
 - [x] librdkafka client configuration: 
 - [x] Operating system: Centos 8 (x64)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ZelinMa557** [comment]
LOG 4 OFFSET [thrd:main]: test_realtime_index [1]: offset reset (at offset 12345 (leader epoch -1), broker 129350) to offset END (leader epoch -1): fetch failed due to requested offset not available on the broker: Broker: Offset out of range

I check the log, it's my problem

**Comment by nhaq-confluent** [comment]
@ZelinMa557 Can this issue be closed then?

**Comment by emasab** [comment]
It seems like the offset that asked set wasn't available in that partition and it triggered an offset reset
