### ISSUE TITLE
mklove/modules/configure.base: line 2126: source: configure.self: file not found on windows 

### ISSUE THREAD

**Issue by manvendrakumarsingh** [confluentinc/librdkafka#4587]
Read the FAQ first: https://github.com/confluentinc/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/confluentinc/librdkafka/discussions

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/confluentinc/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g.,windows 10 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by manvendrakumarsingh** [comment]
Extracting v2.3.0 into tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0... OK
Running 'configure' for librdkafka 2.3.0... ERROR. Please review logs to see
what happened:
----- contents of
'C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/karafka-rdkafka-0.14.7/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/configure.log'
-----
mklove/modules/configure.base: line 2126: source: configure.self: file not found
----- end of file -----
----- contents of 'config.log' -----
DBG 728: tput reports color support: true
DBG 728: Using color escape sequences from tput
DBG 728: Loading module builtin (required by base) from
/c/Ruby27-x64/lib/ruby/gems/2.7.0/gems/karafka-rdkafka-0.14.7/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/librdkafka-2.3.0/mklove/modules/configure.builtin
DBG 728: Loading module host (required by base) from
/c/Ruby27-x64/lib/ruby/gems/2.7.0/gems/karafka-rdkafka-0.14.7/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/librdkafka-2.3.0/mklove/modules/configure.host
DBG 728: Loading module cc (required by base) from
/c/Ruby27-x64/lib/ruby/gems/2.7.0/gems/karafka-rdkafka-0.14.7/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/librdkafka-2.3.0/mklove/modules/configure.cc
DBG 728: Loading module self (required by base) from configure.self
----- end of file -----
rake aborted!
Failed to complete configure task

**Comment by manvendrakumarsingh** [comment]
@edenhill can you please help me to resolve this issue?

**Comment by emasab** [comment]
librdkafka mingw build must use `CMake `and not `mklove `. That's what our pipeline uses too
https://github.com/confluentinc/librdkafka/blob/6d88efd8bc5af9249ea845eab889fb2eb71484c0/packaging/mingw-w64/configure-build-msys2-mingw.sh#L5

**Comment by akiratee** [comment]
hi @emasab I am experiencing the same issue. Can you explain a bit more regarding how to use `CMake instead of `mklove`? I am trying to install the gem waterdrop, and this dependency failed to install.

```
Extracting v2.3.0 into tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0... OK
Running 'configure' for librdkafka 2.3.0... ERROR. Please review logs to see what happened:
----- contents of 'C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/karafka-rdkafka-0.15.1/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/configure.log' -----
mklove/modules/configure.base: line 2126: source: configure.self: file not found
----- end of file -----
----- contents of 'config.log' -----
DBG 1639: tput reports color support: true
DBG 1639: Using color escape sequences from tput
DBG 1639: Loading module builtin (required by base) from /c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/karafka-rdkafka-0.15.1/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/librdkafka-2.3.0/mklove/modules/configure.builtin
DBG 1639: Loading module host (required by base) from /c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/karafka-rdkafka-0.15.1/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/librdkafka-2.3.0/mklove/modules/configure.host
DBG 1639: Loading module cc (required by base) from /c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/karafka-rdkafka-0.15.1/ext/tmp/x86_64-w64-mingw32/ports/librdkafka/2.3.0/librdkafka-2.3.0/mklove/modules/configure.cc
DBG 1639: Loading module self (required by base) from configure.self
----- end of file -----
rake aborted!
Failed to complete configure task
```
