### ISSUE TITLE
Duplicate messages could be received when resuming partitions that weren't paused

### ISSUE THREAD

**Issue by emasab** [confluentinc/librdkafka#4637]
Description
===========
A consumer could start fetching message from a previous offset when partitions were resumed while not paused. That is caused by a stale `rktp_next_fetch_start` that is wrongly used because of the op version bump.

How to reproduce
================
Resume a partition that wasn't paused or modify subscription with the cooperative assignor.
In latter case the partitions that weren't removed aren't paused and can show this bug when the whole assignment is resumed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version 1.x (starting from 1.9.2 or earlier version)
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by kmcclellan** [comment]
Hi! Is this specific to the cooperative assignor, or could it also affect the default assignment strategy (range,roundrobin)? I have seen occasional issues with offset rewinds using 2.3 and would like to know whether an upgrade could fix.
