### ISSUE TITLE
Critical Vulnerabilities identified in librdkafka 

### ISSUE THREAD

**Issue by glansbury** [confluentinc/librdkafka#4664]
Description
===========
Two CVE's with cvss score of 9.8 identified in this library, please help update.

curl 7.86.0
https://github.com/advisories/GHSA-75qm-2q4j-qx6g
https://github.com/confluentinc/librdkafka/blob/master/mklove/modules/configure.libcurl#L48

zlib 1.2.13
https://github.com/advisories/GHSA-mq29-j5xf-cjwr
https://github.com/confluentinc/librdkafka/blob/master/mklove/modules/configure.zlib#L45

How to reproduce
================
Review source code and links provided.  Use any SBOM vulnerability scanner to validate that the libraries are being linked into build.

Initially I discovered this in confluent-kafka-go, however, I believe the vulnerability is coming from the C base library librdkafka

Checklist
=========

 - [x] librdkafka version: `v2.3.0`
 - [x] librdkafka client configuration: `N/A`
 - [x] Operating system: `linux (any base distro)`
 - [x] Provide logs - N/A. links to source code and CVSS all that is required
 - [x] Provide broker log excerpts : N/A
 - [ ] Critical issue: 9.8 CVSS vulnerabilities.

**Comment by mikajylha** [comment]
Related issue #4653

**Comment by mikajylha** [comment]
[Another related issue](https://github.com/confluentinc/confluent-kafka-dotnet/issues/2203) in dotnet lib

**Comment by janjwerner-confluent** [comment]
Thank you for the report. We are in the process of resolving this issue.

**Comment by janjwerner-confluent** [comment]
Resolved in https://github.com/confluentinc/librdkafka/pull/4706
