### ISSUE TITLE
Offset not committed on EOF

### ISSUE THREAD

**Issue by edenhill** [confluentinc/librdkafka#584]
If a KafkaConsumer reaches EOF without seeing any messages, and then closing, no offsets will be committed.

**Comment by jeffwidman** [comment]
I'm sorry for being dense, but why is this bad? If you immediately reach EOF, then you're already at the end... why would you want to commit an offset that's at the same point as the current offset?

**Comment by edenhill** [comment]
I'm not sure, maybe there isnt a use case for this.

**Comment by edenhill** [comment]
I think the initial idea was that if a consumer was started when the partition was empty, hit EOF, then exited, new messages were produced and then it started again it would pick up not from where it left off (the EOF offset) but from auto.offset.reset=latest, thus missing the messages produced.
But auto.offset.reset=earliest solves this, so I'm not sure it is a valid concern.
